vrchatapi/specification

- openapi/components/schemas/Config.yaml
The API can return with this field null. Or at least it was for me.
> Made ConfigDynamicWorldRows.tag nullable

- .github/workflows/ci.yaml
This packages the `openapi.yml` file as a bundled spec and makes it available as artifact.
In the future even linting and validation could ideally be added as CI jobs.
> Run OpenAPI Bundler as GitHub CI task

- openapi.yaml
- openapi/components/schemas/CurrentUser.yaml
- openapi/components/schemas/Date.yaml
- openapi/components/schemas/DateTime.yaml
- openapi/components/schemas/FileVersion.yaml
- openapi/components/schemas/Notification.yaml
- openapi/components/schemas/User.yaml
There is no point in having a DateTime model simply wrapping around a string with format `date-time`. The Model contained requirements for how the timestamp should look like, but that is already hard-defined by the OpenAPI specification:
* `date` – full-date notation as defined by [RFC 3339](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14), section 5.6, for example, 2017-07-21
* `date-time` – the date-time notation as defined by [RFC 3339](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14), section 5.6, for example, 2017-07-21T17:32:28Z
CC @Rexios80 This has a slight chance of affecting your code generation, but ideally it shouldn't.
> Remove redundant wrappers around Date and DateTime

- openapi/components/schemas/User.yaml
> These user fields are nullable

- openapi/components/schemas/Tag.yaml
`language_`-prefixed tags are used for indicating spoken languages (see: vrchat.com website), additionally, I've added the `author_tag_` prefix, which is used on tags provided by the world author themselves.
> Clarify Tag prefixes further

- .github/redocly-plugins/remove-internal.js
- openapi/components/responses/OkSuccess.yaml
- openapi/components/responses/PlayerModerationDeleteOthersError.yaml
- openapi/components/responses/PlayerModerationNotFoundError.yaml
- openapi/components/responses/PlayerModerationRemovedSuccess.yaml
- openapi/components/responses/PlayerModerationUnmoderatedSuccess.yaml
- openapi/components/schemas/PlayerModeration.yaml
- openapi/components/schemas/PlayerModerationID.yaml
- openapi/components/schemas/PlayerModerationType.yaml
- openapi/openapi.yaml
Fixes #9 
Lots of information on the Markdown version of the docs were incorrect/outdated. Endpoints such as `/blocks` and `/unblocks` doesn't exist (anymore).
It also mixed together Moderation (admin) and PlayerModeration (player). Moderation is when you perma-ban or kick someone from the game. PlayerModeration is when you (un)mute, (un)block or show/hide their avatar, and what this PR focuses on documenting.
Calling moderation endpoints should be carefully threaded, as it is suspected muted or blocking someone, especially when many people does it, generates negative scoring in their internal moderation system.
---
**Trivia:** Every person you friend is also added as "unmute" automatically, which is a way to see **when** you friended them. (unless you've accidentally wiped all your …
> feature(playermoderation): add playermoderation api

- openapi/components/schemas/FavoriteType.yaml
Setting `type` as read-only caused it to not show up as as part of the request body for `addFavorite`. Thanks for Devin_Lucashu for helping in finding this.
> fix(favorite): type is not read-only, it is submitted during addFavorite

- openapi/components/parameters.yaml
- openapi/components/paths.yaml
- openapi/components/paths/authentication.yaml
- openapi/components/paths/worlds.yaml
- openapi/components/responses/authentication/MissingParameterError.yaml
- openapi/components/responses/authentication/UserExistsResponse.yaml
- openapi/components/schemas/UserExists.yaml
Fixes #72 
Thanks to @abbeybabbey for discovery and research! <3
> feature: add `checkUserExists` via `/auth/exists` endpoint to search for username/displayName/email

- openapi/components/paths/system.yaml
- openapi/components/schemas/APIConfig.yaml
- openapi/components/schemas/Config.yaml
It seems like VRChat has *finally* disabled Config obfuscation. I don't know if this is temporary, but taking the chance to update the list of real config values. Two new exciting additions here: `disableFrontendBuilds` and `disableOculusSubs`.
Minor additions are `VoiceEnableDegradation`, `VoiceEnableReceiverLimiting` and `dis-countdown`, and the confirmation (and therefore enforcement) of some already existing values.
> feature: add missing API Config fields

- openapi/components/paths/system.yaml
`/api/1/health` now always return:
```json
{
"error":{
"status_code":401
}
}
```
> fix!: deprecate `/health`

- openapi/components/schemas/LimitedWorld.yaml
- openapi/components/schemas/World.yaml
> fix!: number to integer in World and LimitedWorld

- openapi/components/paths/instances.yaml
- openapi/components/schemas/Instance.yaml
- openapi/components/schemas/InstanceID.yaml
- openapi/components/schemas/InstanceType.yaml
- openapi/components/schemas/Region.yaml
Thanks to DemonLionLeo for pointing this out.
> fix!: update Instance docs

- openapi/components/schemas/FileStatus.yaml
Fixes - Invalid value for `value` (queued), must be one of ['waiting', 'complete', 'none'] after creating 2nd file version.
> fix: add missing 'queued' as enum for FileStatus

- openapi/components/schemas/InstanceID.yaml
minLength causing issues with private/offline InstanceIDs
> Removed minLength because was causing issues

- openapi/components/codeSamples/authentication.yaml
- openapi/components/codeSamples/avatars.yaml
- openapi/components/codeSamples/economy.yaml
- openapi/components/codeSamples/favorites.yaml
- openapi/components/codeSamples/files.yaml
- openapi/components/codeSamples/friends.yaml
- openapi/components/codeSamples/instances.yaml
- openapi/components/codeSamples/invite.yaml
- openapi/components/codeSamples/notifications.yaml
- openapi/components/codeSamples/permissions.yaml
- openapi/components/codeSamples/playermoderation.yaml
- openapi/components/codeSamples/system.yaml
- openapi/components/codeSamples/users.yaml
- openapi/components/codeSamples/worlds.yaml
- openapi/components/paths/authentication.yaml
- openapi/components/paths/avatars.yaml
- openapi/components/paths/economy.yaml
- openapi/components/paths/favorites.yaml
- openapi/components/paths/files.yaml
- openapi/components/paths/friends.yaml
- openapi/components/paths/instances.yaml
- openapi/components/paths/invite.yaml
- openapi/components/paths/notifications.yaml
- openapi/components/paths/permissions.yaml
- openapi/components/paths/playermoderation.yaml
- openapi/components/paths/system.yaml
- openapi/components/paths/users.yaml
- openapi/components/paths/worlds.yaml
Fixes vrchatapi/specification#150
Related: vrchatapi/vrchatapi.github.io#120
> feat: add cURL code samples

- openapi/components/schemas/UnityPackage.yaml
By default type integer uses int32 and because of parsers that needs to be int64
``JSON integer 20180420000 is too large or small for an Int32. Path 'world.unityPackages[0].unitySortNumber', line 1, position 2676.``
> Fix unitypackage integer format.

- openapi/components/schemas/World.yaml
Removed AssetUrlObject, PluginUrlObject and UnityPckageUrlObject from World response as VRChat no longer returns those.
> Removed API arguments

- openapi/openapi.yaml
Dependent on https://github.com/vrchatapi/specification/pull/166 being merged first.
> Release 1.7.4

- openapi/components/paths/worlds.yaml
- openapi/components/schemas/World.yaml
Clarifies /worlds/\<id\> works unauthenticated, and the changes in fields that occur from it.
Let me know if I should fix anything, thanks.
Fixes #133
> Clarify /worlds/<id> works unauthenticated, but certain fiels are 0 or empty

- openapi/components/paths/notifications.yaml
Deprecates the `type` query parameter for the `List Notifications` endpoint, as well as tweaks the description.
Let me know if I should fix anything, thanks.
Fixes #170
> Deprecates the type query parameter for the List Notifications endpoint

- openapi/openapi.yaml
Includes the https://github.com/vrchatapi/specification/pull/176 and https://github.com/vrchatapi/specification/pull/175 fixes from Katistic.
> Release 1.7.7

- openapi/components/schemas/APIConfig.yaml
> Allow `announcements` in /config to be empty, and mark as Deprecated

- openapi/components/codeSamples/playermoderation.yaml
- openapi/components/paths/playermoderation.yaml
- openapi/components/schemas/PlayerModerationType.yaml
Removes the `showAvatar` and `hideAvatar` values from `PlayerModerationType` enum. Option to remove them rather than marking them as deprecated was made because marking individual enum values as deprecated have poor SDK generation support. As this is breaking, proposal is to do middle number version increment after this.
* `showAvatar` and `hideAvatar` removed from `PlayerModerationType` enum
* Rewrote/improved documentation section regarding playermoderations in general
* Fixes #188
> Remove mentions of `showAvatar` and `hideAvatar`, and add note of them deprecated

- openapi/components/schemas/User.yaml
This field is not included in the user data received from the websocket
> Removed friendRequestStatus from required user fields

- openapi/components/parameters.yaml
`sortOptions` and `orderOptions` are ignored because they are fixed in #204
> Fix missing description linting in parameters.yaml

- .github/workflows/ci.yaml
This PR updates the deployment process for the specification to allow deploying the documentation to the website without triggering the generation of the SDKs. This allows us to update the documentation more quickly and independently of the SDK generation process, which can be time-consuming due to the extensive testing required.
The new workflow is that any PR going into `main` will be deployed to the website, while SDK generation will only happen once a tag with `release/x.x.x` is created. This also allows us to create other tags, such as `dev/x.x.x` or `archive/removal-of-specific-thing` for testing purposes without generating the SDKs.
> Add documentation deployment without SDK generation

- .github/workflows/ci.yaml
Logic error, where it was checking if ref is **both** "main" and the tag, which can never happen.
> Fix CI logic to allow building SDK

- openapi/components/schemas/AccountDeletionLog.yaml
- openapi/components/schemas/CurrentUser.yaml
VRChat has added `accountDeletionLog` field to the `CurrentUser` object. This field contains a list of AccountDeletionLog entries, which are shown below. The list itself may be `null` if the user has never requested deletion.
Example:
accountDeletionLog |  
-- | --
0 |  
message | "Deletion requested"
deletionScheduled | "2022-12-19T18:06:16.333Z"
dateTime | "2022-12-05T18:06:16.335Z"
1 |  
message | "Deletion canceled"
dateTime | "2022-12-05T18:06:31.190Z"
> Add accountDeletionLog to CurrentUser

- openapi/components/paths.yaml
- openapi/components/paths/authentication.yaml
The "Delete User" (used to mark yourself for deletion) has moved from `user` to `users`.
Another question is why this is under AuthenticationAPI, and not UsersAPI, as it is a /users endpoint, but that is out of scope of this PR.
> DeleteUser has moved from `user` to `users`

- openapi/components/paths/playermoderation.yaml
PlayerModartions of type `showAvatar` and `hideAvatar` has already been deprecated in October, as stated further down the file. This PR only removes the examples still using these deprecated types.
> Remove legacy mention of avatar playermoderation

- .github/workflows/ci.yaml
The step before installs all dependencies as v16. When the next step then tries to fetch v14, they don't exist. This worked for a few weeks after the change that broke it, because the old cache persisted. But now the v14 cache is gone, which is why it suddenly broke.
> Fix GitHub CI

- openapi/components/paths/groups.yaml
groups/joins returns the Newly created Group Member, not the just joined Group.
> Change response in /groups/join/ endpoint to return GroupMember

- openapi/components/schemas/APIConfig.yaml
- openapi/components/schemas/APIConfigDownloadURLList.yaml
```json
{
...
"downloadUrls": {
"sdk2": "https://assets.vrchat.com/sdk/VRCSDK2-2022.04.20.16.27_Public.unitypackage",
"sdk3-worlds": "https://assets.vrchat.com/sdk/VRChat-Worlds-SDK-3.2.0.unitypackage",
"sdk3-avatars": "https://assets.vrchat.com/sdk/VRChat-Avatars-SDK-3.2.0.unitypackage",
"vcc": "https://vrcpm.vrchat.cloud/vcc/Builds/2.1.1/VRChat_CreatorCompanion_Setup_2.1.1.exe",
"bootstrap": "https://github.com/vrchat/packages/releases/download/resolvers/latest-resolver.unitypackage"
},
}
> fix: APIConfigDownloadURLList now includes vcc and bootstrap

- openapi/components/paths/groups.yaml
- openapi/components/responses/groups/LimitedGroupListResponse.yaml
- openapi/components/schemas/LimitedGroup.yaml
> Group Search API

- openapi/components/schemas/CurrentUserPresence.yaml
- openapi/components/schemas/NotificationType.yaml
This notification type appears to be used for system messages, e.g., VRC+ gift notifications. The type-specific payload seems to be rather arbitrary, so I will be looking into that more.
> Add 'message' notification type to enum

- openapi/components/schemas/LimitedUser.yaml
Closes https://github.com/vrchatapi/specification/issues/273
Unfortunately I don't have sample json with these missing, but we do have Firebase Crashlytics logs of this happening with real users
> LimitedUser image fields shouldn't be required

- openapi/components/schemas/GroupLimitedMember.yaml
- openapi/components/schemas/GroupMember.yaml
The lastPostReadAt field for group members can be null through inspection of the api responses.
> fix: fix lastPostReadAt nullability for GroupMember

- openapi/components/schemas/GroupMember.yaml
Specify that GroupMember joinedAt can be nullable since it is null for the GroupMembers returned from `/groups/{groupId}/bans`
> fix(group): specify joinedAt as nullable

- openapi/components/requests/RespondGroupJoinRequest.yaml
- openapi/components/schemas/GroupJoinRequestAction.yaml
Add an enum for GroupJoinRequestAction instead of having it be an unconstrained string.
> refactor(group): add an enum for GroupJoinRequestAction

- openapi/components/schemas/GroupMemberStatus.yaml
Add "banned" to GroupMembershipStatus. This shows up on `/groups/{groupId}/bans`.
> fix(group): add "banned" to GroupMembershipStatus

- openapi/components/schemas/GroupMemberLimitedUser.yaml
Specify that currentAvatarThumbnailImageUrl on a GroupMemberLimitedUser is nullable.
> fix(group): specify that currentAvatarThumbnailImageUrl is nullable

- openapi/components/paths/instances.yaml
- openapi/components/responses/instances/InstanceCloseForbiddenError.yaml
- openapi/components/schemas/Instance.yaml
Document the closeInstance endpoint.
> feat(instance): document the closeInstance endpoint

- openapi/components/paths/groups.yaml
- openapi/components/responses/groups/GroupInviteBadRequestError.yaml
- openapi/components/responses/groups/GroupInviteForbiddenError.yaml
- openapi/components/responses/groups/GroupJoinRequestResponseBadRequestError.yaml
Document some more error responses for group endpoints.
> feat(group): document more error responses

- openapi/components/schemas/Instance.yaml
- openapi/components/schemas/InstanceOwnerId.yaml
Specify that an instance's ownerId can be a groupId or null depending on the instance type.
> fix(instance): specify that ownerId can be groupId or null

- openapi/components/schemas/Instance.yaml
Make roleRestricted not a required property since it isn't always returned depending on the instance type.
> fix(instance): make roleRestricted not required

- openapi/components/schemas/GroupMemberLimitedUser.yaml
Specify that a GroupMemberLimitedUsers's thumbnailUrl can be null as seen in multiple real vrchat responses.
> fix(groups): specify that GroupMemberLimitedUser's thumbnailUrl can be null

- openapi/components/paths.yaml
- openapi/components/paths/groups.yaml
- openapi/components/requests/CreateGroupPostRequest.yaml
- openapi/components/responses/groups/DeleteGroupPostResponse.yaml
- openapi/components/responses/groups/GroupPostResponse.yaml
- openapi/components/schemas/GroupPost.yaml
- openapi/components/schemas/GroupPostVisibility.yaml
Hi, please review my homework.
Added two new paths into the specification.
1. /groups/{groupId}/posts
2. /groups/{groupId}/posts/{notificationId}
First one adds a GET and POST request for getting a list of posts from a group, and creating a new post. They are similar to the announcements functions, but perhaps hints that the "announcements" are becoming deprecated in the  near future. The announcements path still functions (partially), but the website's front end doesn't really reflect back anything useful.
The second path creates a DELETE request for removing a post. They use the notification ID system, which is interesting.
The POST and DELETE methods probably both have a 403 error attached to them, but I haven't been able to test this without going into a random group's posts to …
> Added support for group posts controls

- .redocly.yaml
- .spectral.yaml
- openapi/components/schemas/_index.yaml
- openapi/openapi.yaml
- package-lock.json
- package.json
Ensure the notification details schemas are included in the bundled spec.
Update to @redocly/cli which replaces @redocly/openapi-cli.
https://www.npmjs.com/package/@redocly/openapi-cli
This is necessary to bring in fixes for the bundler not properly including refs when adding extra schemas.
Fixes: #317
> fix(notification):  Include notification details

- openapi/components/paths/users.yaml
Changed the /users/{userId}/groups response to a LimitedGroupListResponse.yaml since the returned schema is less than the Groups.yaml.
Example:
```
"id": "gmem_adac4f98-2bc2-4055-a67b-0db0cdaf9bc5",
"name": "Club Pnk",
"shortCode": "PNK",
"discriminator": "6939",
"description": "Welcome to Club Pnk‚ the cutting-edge Australian-based virtual reality night club that is revolutionizing the nightlife scene․ \n\nAs the doors of the physical world close‚ our digital doors open wide‚ offering an immersive and unforgettable experience that transcends boundaries and defies limitations․\n\nClub Pnk beckons you into an electrifying environment‚ where you can lose yourself to the rhythm and connect with fellow partygoers from all corners of the globe․\n\nAs an Australian-based virtual reality night …
```
> Change user groups to LimitedGroup response.

- openapi/components/requests/UpdateUserRequest.yaml
- openapi/components/responses/notifications/SendNotificationResponse.yaml
- openapi/components/schemas/CurrentUser.yaml
- openapi/components/schemas/LimitedUser.yaml
- openapi/components/schemas/SentNotification.yaml
CurrentUser: badge?
badge field is not required: https://github.com/vrchatapi/specification-test/blob/b55c7d639f4d11167cdc0195170494db90b61cec/data/requests/avatars/selectavatar-with-id.md
LimitedUser: +bioLinks, +currentAvatarTags
SentNotification:  recieverUserId -> receiverUserId, details: object (was string)
POST `/invite/myself/to/{worldid}:{instanceid}`:
```json
{
"created_at": "2024-05-05T08:02:42.772Z",
"details": {
"worldId": "wrld_4cf554b4-430c-4f8f-b53e-1f294eed230b:80187~group(grp_9b1b2366-0eb6-41cb-9235-470b0db83f99)~groupAccessType(public)~region(us)",
"worldName": "The Black Cat"
},
"id": "not_093fbb9f-5d71-47d3-995a-0032cda17450",
"message": "This is a generated invite to The Black Cat",
"receiverUserId": "usr_9664d091-ca57-43a5-8524-6a8f2a14de48",
"senderUserId": …
```
> Add fields to LimitedUser, change fields in SentNotification, make CurrentUser.badges not required

- openapi/components/paths/users.yaml
- openapi/components/responses/users/LimitedUserGroupListResponse.yaml
- openapi/components/schemas/LimitedUserGroups.yaml
As it turns out, querying for the user groups returns a very very slightly different object than LimitedGroup. Since the schema is different, changing the response into its own schema.
> FIX: User Groups is not LimitedGroups object

- openapi/components/requests/CreateInstanceRequest.yaml
- openapi/components/schemas/Instance.yaml
- openapi/components/schemas/InstanceRegion.yaml
Separately define the instance region to explicitly enumerate the allowed instance regions.
This helps make it clear what types of regions are allowed when creating instances with the vrc api.
Example response when trying to create an instance with a region that isn't allowed:
```
{
"error": {
"message": "region must be one of ［＂us＂‚＂use＂‚＂eu＂‚＂jp＂］‚ not ＂usw＂",
"status_code": 400
}
}
```
> refactor(instance): separately define the instance region

- openapi/components/schemas/GroupLimitedMember.yaml
Specify that joinedAt is nullable when a user is not a member when using the endpoint `/groups/{groupId}/members/{userId}`
> fix(group): specify joinedAt is nullable

- openapi/components/schemas/UnityPackage.yaml
Occasionally, a VRC World object will produce UnityAsset's with empty (but not null) string: `""` assetURL values, which will trigger a validation error (at least on the Python SDK)
This PR removes the minimum character check for Unity Asset URL's
Related issue: https://github.com/vrchatapi/specification/issues/341
> Remove minimum length from assetUrl

- openapi/components/schemas/FileData.yaml
Fixes #349 I believe.
FileData is only used in FileVersion as of now, so this shouldn't break anything else
> Remove md5 requirement breaking some requests on validation

- openapi/components/paths/groups.yaml
The endpoint can return multiple 403 errors:
- You're not allowed to view membership details
- You're not a member
However with the state of `oneOf` I just decided to put something there.
I hope that both responses can be parsed to an error regardless of the actual errormessage contents. 
Fixes: #350
> Add 403 mapping for getting Group members

- openapi/components/schemas/Group.yaml
- openapi/components/schemas/GroupMyMember.yaml
Please note, that I temporarily guessed the types of:
- myMember/lastPostReadAt
- myMember/acceptedById
- myMember/acceptedByDisplayName
- myMember/mRoleIds
- lastPostCreatedAt
- transferTargetId
When looking at the repsonse I get from https://vrchat.com/api/1/groups/{groupid} in the vrchat website, I can't find `transferTargetId`, `myMember/acceptedByDisplayName`, `myMember/acceptedById` or `myMember/hasJoinedFromPurchase`.
> Add new Group properties

- openapi/components/parameters.yaml
- openapi/components/paths/groups.yaml
Added the `roleId` query-string to `groups.yaml` and `parameters.yaml` for `/groups/{groupId}/members` since I noticed it wasn't documented.
> Add missing query-string `roleId` to `/groups/{groupId}/members`

- openapi/components/codeSamples/economy.yaml
- openapi/components/paths.yaml
- openapi/components/paths/economy.yaml
- openapi/components/responses/economy/LicenseGroupListResponse.yaml
```
returns 
{
"error": {
"message": "\"Invalid Admin Credentials\"",
"status_code": 403
}
}
```
> Remove licenseGroup endpoint as it's admin only

- openapi/components/codeSamples/notifications.yaml
- openapi/components/paths.yaml
- openapi/components/paths/notifications.yaml
- openapi/components/responses/notifications/NotificationNotFoundError.yaml
> Add notification get endpoint

- openapi/components/schemas/GroupMember.yaml
- openapi/components/schemas/GroupMyMember.yaml
Specify that some recently added GroupMember fields are nullable through observeration of api responses.
> fix(group): specify some GroupMember fields are nullable

- openapi/components/codeSamples/favorites.yaml
- openapi/components/codeSamples/files.yaml
- openapi/components/codeSamples/users.yaml
- openapi/components/parameters.yaml
- openapi/components/paths.yaml
- openapi/components/paths/favorites.yaml
- openapi/components/paths/files.yaml
- openapi/components/paths/users.yaml
- openapi/components/requests/UpdateUserNoteRequest.yaml
- openapi/components/responses/favorites/FavoriteLimitsResponse.yaml
- openapi/components/responses/files/FileAnalysisResponse.yaml
- openapi/components/responses/users/FeedbackListResponse.yaml
- openapi/components/responses/users/UserNoteListResponse.yaml
- openapi/components/responses/users/UserNoteResponse.yaml
- openapi/components/schemas/FavoriteGroupLimits.yaml
- openapi/components/schemas/FavoriteLimits.yaml
- openapi/components/schemas/Feedback.yaml
- openapi/components/schemas/FeedbackID.yaml
- openapi/components/schemas/FileAnalysis.yaml
- openapi/components/schemas/FileAnalysisAvatarStats.yaml
- openapi/components/schemas/UserNote.yaml
- openapi/components/schemas/UserNoteID.yaml
`GET /auth/user/favoritelimits`
`GET /analysis/{fileId}/{versionId}`
`GET /analysis/{fileId}/{versionId}/security`
`GET /analysis/{fileId}/{versionId}/standard`
`GET /users/{userId}/feedback`
`GET /userNotes`
`POST /userNotes`
`GET /userNotes/{userNoteId}`
+ fixed incorrect example request method
+ fixed typo in path variable
> User- and file-related endpoints

- openapi/components/codeSamples/users.yaml
- openapi/components/paths.yaml
- openapi/components/paths/users.yaml
- openapi/components/responses/users/UserGroupInstanceListResponse.yaml
- openapi/components/responses/users/UserMustBeOwnError.yaml
An updated version of #329 that is tested with the C# api and validated to work
> Add User Group Instances endpoint

- openapi/components/requests/CreateGroupRoleRequest.yaml
- openapi/components/requests/UpdateGroupRoleRequest.yaml
- openapi/components/schemas/AgeVerificationStatus.yaml
- openapi/components/schemas/CurrentUser.yaml
- openapi/components/schemas/Group.yaml
- openapi/components/schemas/GroupMyMember.yaml
- openapi/components/schemas/GroupPermissions.yaml
- openapi/components/schemas/GroupRole.yaml
- openapi/components/schemas/User.yaml
Add enum values for ageVerificationStatus (user). added ageVerificationSlotsAvailable (groups)
> Add ageVerificationSlotsAvailable, Improve ageVerificationStatus

- openapi/components/parameters.yaml
- openapi/components/paths/groups.yaml
- openapi/components/schemas/GroupAuditLogEntry.yaml
> Add parameters to /groups/{groupId}/auditLogs

- openapi/components/paths/groups.yaml
- openapi/components/responses/groups/GroupPostsResponse.yaml
Previous version doesnt work at all right now, technically breaking change due to name change but the old name was wrong
> Fix group posts api

- openapi/components/codeSamples/avatars.yaml
- openapi/components/codeSamples/users.yaml
- openapi/components/parameters.yaml
- openapi/components/paths.yaml
- openapi/components/paths/avatars.yaml
- openapi/components/paths/users.yaml
- openapi/components/requests/ChangeUserTagsRequest.yaml
- openapi/components/requests/UpdateUserBadgeRequest.yaml
- openapi/components/responses/avatars/AvatarImpostorEnqueueResponse.yaml
- openapi/components/responses/avatars/AvatarImpostorQueueStatsResponse.yaml
- openapi/components/responses/users/UserBadgeUpdateResponse.yaml
- openapi/components/responses/users/UserTagInvalidError.yaml
- openapi/components/schemas/LimitedBadge.yaml
- openapi/components/schemas/ServiceQueueStats.yaml
- openapi/components/schemas/ServiceStatus.yaml
`GET /avatars/licensed`
`POST /avatars/{avatarId}/impostor/enqueue`
`DELETE /avatars/{avatarId}/impostor`
`GET /avatars/impostor/queue/stats`
`POST /users/{userId}/addTags`
`POST /users/{userId}/removeTags`
`GET /users/{userId}/{worldId}/persist/exists`
`DELETE /users/{userId}/{worldId}/persist`
`POST /users/{userId}/badges/{badgeId}`
Addresses #423
> Added endpoints for licensed avatars, impostors, user tags, user persistence, badge visibility

- openapi/components/schemas/CurrentUser.yaml
> Remove `currentAvatarAssetUrl` from CurrentUser schema

- openapi/components/codeSamples/files.yaml
- openapi/components/paths.yaml
- openapi/components/paths/files.yaml
- openapi/components/schemas/File.yaml
Note: Currently a draft because it can only be merged once all generators are confirmed to work with it.
My current edits to the generators assume files are .png.
Generators:
> [DRAFT] Add image endpoints

- openapi/components/codeSamples/authentication.yaml
- openapi/components/paths.yaml
- openapi/components/paths/authentication.yaml
- openapi/components/paths/instances.yaml
- openapi/components/paths/users.yaml
- openapi/components/requests/UpdateUserRequest.yaml
- openapi/components/responses/authentication/Get2FARecoveryCodesResponse.yaml
- openapi/components/responses/users/CurrentPasswordRequiredError.yaml
- openapi/components/schemas/CurrentUser.yaml
- openapi/components/schemas/TwoFactorRecoveryCodes.yaml
Addresses #427
Adds `GET /auth/twofactorauth/otp`
Adds properties to CurrentUser and UpdateUserRequest
> Authentication and User Update properties

- openapi/components/paths/invite.yaml
- Fixes the current endpoint descriptions incorrectly suggesting these endpoints send out world invites.
- Adds some additional context regarding the `responseSlot` parameter, and what message will be used. 
That last one _would_ probably better fit as a description on the body / property itself, however swagger nor rapidoc seem to render these for request bodies in multipart requests. Or at least, I could not get them to, so I've put it in the endpoint description for both to stay consistent.
> Clarify endpoint descriptions for "Respond Invite" and "Respond Invite with Photo" 

- openapi/components/paths.yaml
- openapi/components/paths/favorites.yaml
- openapi/components/paths/groups.yaml
- openapi/components/responses/groups/GroupRoleTemplatesResponse.yaml
- openapi/components/schemas/GroupRoleTemplateValues.yaml
> Add role templates, favorite groups query param

- openapi/components/codeSamples/authentication.yaml
- openapi/components/parameters.yaml
- openapi/components/paths.yaml
- openapi/components/paths/authentication.yaml
- openapi/components/requests/RegisterUserAccountRequest.yaml
- openapi/components/requests/ResendEmailConfirmationRequest.yaml
- openapi/components/responses/authentication/ConfirmEmailResponse.yaml
- openapi/components/responses/authentication/Disable2FAResponse.yaml
- openapi/components/responses/authentication/Pending2FAResponse.yaml
- openapi/components/responses/authentication/ResendVerificationEmailSuccess.yaml
- openapi/components/responses/authentication/VerifyLoginPlaceResponse.yaml
- openapi/components/schemas/CurrentUser.yaml
- openapi/components/schemas/Disable2FAResult.yaml
- openapi/components/schemas/Pending2FAResult.yaml
- openapi/components/schemas/Verify2FAResult.yaml
> More authentication endpoints

- openapi/components/paths/avatars.yaml
- openapi/components/paths/files.yaml
- openapi/components/requests/CreateAvatarRequest.yaml
- openapi/components/responses/avatars/UnableToCreateAvatarNowError.yaml
- openapi/components/schemas/Avatar.yaml
- openapi/components/schemas/LimitedWorld.yaml
- openapi/components/schemas/LocalDateTime.yaml
- openapi/components/schemas/StoreID.yaml
- openapi/components/schemas/TiliaStatus.yaml
- openapi/components/schemas/World.yaml
> Avatar, Tilia, Emoji updates & fixes

- openapi/components/responses/files/RawFileResponse.yaml
Closes #460 
Right now only does image because I have not been able to download vrca/unitypackage, and I dont think they want us to be able to using the api. and for now image is better than nothing anyways.
> Add image file downloads

- openapi/components/paths.yaml
- openapi/components/paths/groups.yaml
- openapi/components/responses/groups/UpdateGroupRepresentationSuccess.yaml
This endpoint seemed to be missing from the docs, so I've tried to add it.
> Document `PUT /groups/:groupId/representation` endpoint

- openapi/components/requests/RequestInviteRequest.yaml
Addresses #477
Sorry for duplicate, apparently renaming branch from the github default closes the pr
> Rename messageSlot to requestSlot in requestInviteRequest
