vrchatapi/specification

- openapi.yaml
- openapi/components/schemas/CurrentUser.yaml
- openapi/components/schemas/Error.yaml
- openapi/components/schemas/LimitedUser.yaml
- openapi/components/schemas/Notification.yaml
- openapi/components/schemas/NotificationDetailInvite.yaml
- openapi/components/schemas/NotificationID.yaml
- openapi/components/schemas/Response.yaml
- openapi/components/schemas/Success.yaml
- openapi/components/schemas/Tag.yaml
- openapi/components/schemas/User.yaml
- openapi/components/schemas/UserID.yaml
* Fixed Tag references in User objects
* **Added Notification endpoints**
* Split up Error and Success responses into individual responses for more clear and 1:1 examples
> Add Notification endpoints

- openapi/components/parameters.yaml
- openapi/components/paths/invite.yaml
- openapi/components/paths/notifications.yaml
- openapi/components/responses/invite/InviteAlreadyRespondedError.yaml
- openapi/components/responses/invite/InviteCannotRespondSelfError.yaml
- openapi/components/responses/invite/InviteMustBeFriendsError.yaml
- openapi/components/responses/invite/InviteResponseSlotOutOfBounds.yaml
- openapi/components/schemas/Notification.yaml
- openapi/components/schemas/NotificationDetailInvite.yaml
- openapi/components/schemas/NotificationDetailInviteResponse.yaml
- openapi/components/schemas/NotificationDetailRequestInvite.yaml
- openapi/components/schemas/NotificationDetailRequestInviteResponse.yaml
- openapi/components/schemas/NotificationType.yaml
> Add Invite, RequesttInvite and Respond endpoints

- openapi/components/parameters.yaml
- openapi/components/paths.yaml
- openapi/components/paths/system.yaml
- openapi/components/responses/system/DownloadSourceCodeAccessError.yaml
> feature: add JS and CSS download endpoints

- openapi/components/schemas/APIConfig.yaml
- openapi/components/schemas/Avatar.yaml
- openapi/components/schemas/CurrentUser.yaml
- openapi/components/schemas/FileData.yaml
- openapi/components/schemas/FileVersion.yaml
- openapi/components/schemas/Instance.yaml
- openapi/components/schemas/Response.yaml
- openapi/components/schemas/UnityPackage.yaml
> chore!: replace number with integer where possible

- openapi/components/paths/system.yaml
> docs: update /time and /visits documentation, no longer plain

- openapi/components/parameters.yaml
- openapi/components/paths.yaml
- openapi/components/paths/invite.yaml
- openapi/components/requests/UpdateInviteMessageRequest.yaml
- openapi/components/responses/invite/InviteMessageGetNegativeSlotError.yaml
- openapi/components/responses/invite/InviteMessageGetTooHighSlotError.yaml
- openapi/components/responses/invite/InviteMessageInvalidSlotNumberError.yaml
- openapi/components/responses/invite/InviteMessageNoEntryForSlotError.yaml
Fixes #104 
Thanks to @Katistic for pointing these out.
Expanded documentation regarding the entire "Slot" system will be added in the future. But that has lower priority than adding some of the completely undocumented endpoints.
> docs: fix Invite Message-related documentation

- openapi/components/paths.yaml
> fix!: fix CSS asset path

- openapi/components/schemas/CurrentAvatarImageUrl.yaml
- openapi/components/schemas/CurrentAvatarThumbnailImageUrl.yaml
- openapi/components/schemas/CurrentUser.yaml
- openapi/components/schemas/LimitedUser.yaml
- openapi/components/schemas/User.yaml
Fixes #113 
Add description and example.
> feature: add avatarImageUrl description

- openapi/components/parameters.yaml
- openapi/components/paths.yaml
- openapi/components/paths/system.yaml
- openapi/components/responses/system/InfoPushListResponse.yaml
- openapi/components/schemas/APIConfig.yaml
- openapi/components/schemas/DynamicContentRow.yaml
- openapi/components/schemas/InfoPush.yaml
- openapi/components/schemas/InfoPushData.yaml
- openapi/components/schemas/InfoPushDataClickable.yaml
- openapi/components/schemas/ReleaseStatus.yaml
> feature: add IPS endpoint

- openapi/components/schemas/Region.yaml
Fix for this error:
2021-11-30T07:36:56.051023ZDioError [DioErrorType.other]: Deserializing '[id, wrld_033b9f75-49be-4213-9218-a540dd2be60a:22183, location, wrld_033b9f75...' to 'Instance' failed due to: Deserializing 'unknown' to 'Region' failed due to: Invalid argument(s): unknown #0 BuiltJsonSerializers._deserialize (package:built_value/src/built_json_serializers.dart:178) #1 BuiltJsonSerializers.deserialize (package:built_value/src/built_json_serializers.dart:124) #2 WorldsApi.getWorldInstance (package:vrchat_dart_generated/src/api/worlds_api.dart:776) <asynchronous suspension> #3 VrchatUtils.buildInstanceInfo (package:kitsune_waifu_reborn/util/vrchat_utils.dart:32) <asynchronous suspension> #4 VrchatCommandResponder._respondToOnlineCommand …
> fix: add missing Region type "unknown"

- openapi/components/paths/files.yaml
> fix: `partNumber` can be optional

- openapi/components/schemas/InstanceID.yaml
I hope I did it correctly. Still trying to understand fully how this works.
> Fixed InstanceID - Added private as option for instanceID

- openapi/components/paths/playermoderation.yaml
- openapi/components/schemas/PlayerModerationType.yaml
Thanks to @naqtn for bringing this to attention, and Redacted for help with discovery.
> feat(avatarDynamics): add playerModeration types for avatar interact

- openapi/components/schemas/CurrentUser.yaml
> Made twoFactorAuthEnabledDate is nullable

- openapi/components/parameters.yaml
> fix: correct type for parameter "feature"

- openapi/components/codeSamples/instances.yaml
- openapi/components/codeSamples/invite.yaml
- openapi/components/paths.yaml
- openapi/components/paths/instances.yaml
- openapi/components/paths/invite.yaml
- openapi/components/requests/InviteMyselfToRequest.yaml
- openapi/components/responses/notifications/SendNotificationResponse.yaml
- openapi/components/schemas/SentNotification.yaml
Fixes issues in:
126a434471b831f6b26e8b7a49fd7afe32291d7c
03b3649a050ec7d22f8582aaae36c555b579788c
497a5b09b0be780fd952902e4ae7d8fdf017647a
> Fix several issues regarding previous commits

- openapi/openapi.yaml
* Pre-PR to speed up approval. Technical result of branch restriction reasons.
* Pending merge of #189
> Release 1.9.0

- .spectral.yaml
- functions/print.js
- functions/schema_object_name_mismatch_filename.js
- openapi/components/parameters.yaml
- openapi/components/paths/avatars.yaml
- openapi/components/paths/worlds.yaml
- openapi/components/schemas/APIConfig.yaml
- openapi/components/schemas/APIConfigAnnouncement.yaml
- openapi/components/schemas/APIConfigDownloadURLList.yaml
- openapi/components/schemas/APIConfigEvents.yaml
- openapi/components/schemas/FriendStatus.yaml
- openapi/components/schemas/GroupJoinState.yaml
- openapi/components/schemas/GroupPrivacy.yaml
- openapi/components/schemas/GroupRoleTemplate.yaml
- openapi/components/schemas/InfoPushData.yaml
- openapi/components/schemas/InfoPushDataArticle.yaml
- openapi/components/schemas/InfoPushDataArticleContent.yaml
- openapi/components/schemas/Instance.yaml
- openapi/components/schemas/InstancePlatforms.yaml
- openapi/components/schemas/OrderOption.yaml
- openapi/components/schemas/SortOption.yaml
- openapi/components/schemas/VerifyAuthTokenResult.yaml
- package-lock.json
Once we release Groups API, we will definitively need to do a bigger version number jump than just patch version.
> Add title linting and fix resulting "title" errors

- .github/workflows/ci.yaml
- openapi/openapi.yaml
Releases 1.10.0
This also includes part of the CI that was missing from previous PR.
> Release 1.10.0

- openapi/components/schemas/GroupGalleryID.yaml
> Group Gallery wrong ID fix

- openapi/components/codeSamples/authentication.yaml
- openapi/components/paths.yaml
- openapi/components/paths/authentication.yaml
- openapi/components/requests/TwoFactorEmailCode.yaml
- openapi/components/responses/authentication/Verify2FAEmailCodeResponse.yaml
- openapi/components/schemas/Verify2FAEmailCodeResult.yaml
Add `auth/twofactorauth/emailotp/verify` endpoint
Fixes #218
> Add "Verify Email Code" endpoint

- CODE_OF_CONDUCT.md
- openapi/openapi.yaml
Swapping the associated emails in an effort mitigate spam emails.
> chore: update emails

- openapi/components/schemas/CurrentUser.yaml
- openapi/components/schemas/ReleaseStatus.yaml
- fix: CurrentUser accountDeletionLog is nullable
- fix: releaseStatus can be all
> releaseStatus

- openapi/components/schemas/LimitedUser.yaml
- openapi/components/schemas/World.yaml
Added Recommended Capacity to World
Removed fallbackAvatar from LimitedUser
> Update API Fields

- openapi/components/paths/groups.yaml
Add pagination parameters for group requests and invites.
> fix(groups): add pagination parameters for requests and invites

- openapi/components/schemas/GroupLimitedMember.yaml
- openapi/components/schemas/GroupMember.yaml
Use GroupMemberStatus status for GroupMember and GroupMemberLimited membershipStatus.
> refactor(group): use GroupMemberStatus enum for GroupMember

- openapi/components/schemas/Instance.yaml
Add some properties that were missing from the spec but are returned by the api.
> feat(instance): add missing instance properties

- openapi/components/paths/authentication.yaml
Specify when the request body is required for the vrchat authentication requests.
> fix(authentication): specify required request body where necessary

- openapi/components/paths/playermoderation.yaml
Specify when the request body is required for the vrchat playermoderation requests.
> fix(playermoderation): specify required request body where necessary

- openapi/components/paths/invite.yaml
Specify when the request body is required for the vrchat invite requests.
> fix(invite): specify required request body where necessary

- openapi/components/paths/groups.yaml
Specify when the request body is required for the vrchat group requests.
> fix(group): specify required request body where necessary

- openapi/components/schemas/World.yaml
> World namespace is nullable

- openapi/components/paths/friends.yaml
- openapi/components/responses/friends/FriendBadRequestError.yaml
Document more friend endpoint error responses
> feat(friends): document more friend endpoint error responses

- openapi/components/paths/instances.yaml
- openapi/components/requests/CreateInstanceRequest.yaml
- openapi/components/schemas/GroupAccessType.yaml
- openapi/components/schemas/Instance.yaml
Document the create instance endpoint
> feat(instance): document the create instance endpoint

- openapi/components/paths/groups.yaml
- openapi/components/responses/groups/GroupInstanceListResponse.yaml
- openapi/components/schemas/GroupInstance.yaml
Document the group instances endpoint.
Fixes: #270
> feat(group): document the group instances endpoint

- openapi/components/requests/CreateInstanceRequest.yaml
Use the InstanceOwnerId ref in CreateInstanceRequest
> chore(instance): use the InstanceOwnerId ref in CreateInstanceRequest

- openapi/components/paths/groups.yaml
- openapi/components/responses/groups/BanGroupMemberBadRequestError.yaml
Document a bad request error case for group ban.
> chore(groups): document bad request error for group ban

- openapi/components/paths.yaml
Add the group instances endpoints to paths.
Fixes: #270
> fix(groups): add the group instances endpoint to paths

- openapi/components/paths/groups.yaml
- openapi/components/responses/groups/DeleteGroupInviteBadRequestError.yaml
Document one error response for the delete group invite endpoint
> chore(groups): document error for delete group invite endpoint

- openapi/components/paths.yaml
- openapi/components/requests/CreateInstanceRequest.yaml
Add missing instances path that I added in
https://github.com/vrchatapi/specification/pull/305
> fix(instances): add missing instances path

- openapi/components/requests/CreateInstanceRequest.yaml
Document more create instance parameters as specified in: https://ask.vrchat.com/t/developer-update-2-may-2024/24284
> feat(instance): document more create instance parameters

- openapi/components/paths/groups.yaml
- openapi/components/requests/RespondGroupJoinRequest.yaml
Document blocked join requests
> feat(groups): document blocked join requests

- openapi/components/schemas/User.yaml
Remove badges from required fields on user as it is not always present
> fix(user): remove badges from required fields

- openapi/components/schemas/GroupAccessType.yaml
Change the group access type from member to members
> fix(group): fix group access type to members

- openapi/components/schemas/GroupMemberStatus.yaml
Add userblocked status to GroupMemberStatus
> fix(group): add userblocked status to GroupMemberStatus

- openapi/components/schemas/User.yaml
see https://github.com/vrchatapi/specification-test/blob/1a3fa9ea1bae2584a6894ab2d749092c4f210f32/data/requests/users/getuser.md
> Add `platform` to `User`

- .github/workflows/sdk_generate.yaml
Also fix invalid matrix variable reference
> Add dart to sdk generation dispatch

- openapi/components/schemas/User.yaml
See CI failure here: https://github.com/vrchatapi/vrchatapi-dart/actions/runs/10032403684/job/27724052755?pr=17#step:6:50
This was introduced in https://github.com/vrchatapi/specification/pull/351
> Remove `platform` from required fields on `User`

- openapi/components/responses/permissions/PermissionListResponse.yaml
- openapi/components/schemas/Permission.yaml
I did not add a description, because I did not know what to put there.
> Add `ownerDisplayName` to Permission.yaml

- openapi/components/parameters.yaml
- openapi/components/paths/worlds.yaml
Fixes: #249
I didn't put a description in the fuzzy parameter, because I don't quite know what it does.
> Add fuzzy parameter to world search

- openapi/components/paths/groups.yaml
- openapi/components/responses/NoPermission.yaml
Fixes: https://github.com/vrchatapi/specification/issues/253
> Add 403 mapping for group bans

- openapi/components/schemas/TransactionAgreement.yaml
as per https://github.com/vrchatapi/specification-test/blob/ed3be46eed50614e5ccc33aae43af20837c86dc0/data/requests/economy/getsteamtransactions.md
> Add  `agreement` to TransactionAgreement.yaml

- openapi/components/schemas/User.yaml
Reverts vrchatapi/specification#359
> Revert "Remove `platform` from required fields on `User`"

- openapi/components/schemas/InstanceRegion.yaml
Fixes https://github.com/vrchatapi/specification/issues/376
> Add instance region `unknown`

- openapi/components/schemas/User.yaml
Fixes https://github.com/vrchatapi/specification/issues/378
> User platform is not required

- openapi/components/schemas/CurrentUser.yaml
- openapi/components/schemas/CurrentUserPresence.yaml
- openapi/components/schemas/User.yaml
-  add nullable string `last_mobile`
-  remove required status for `platform`
- add nullable string `queuedInstance`
- add boolean `receiveMobileInvitations`
- add string `currentAvatarTags` (comma-delimited concatenation of avatar tags)
- add nullable string `debugflag`
- add nullable string `userIcon`
> Update properties: User, CurrentUser, CurrentUserPresence

- openapi/components/schemas/Region.yaml
Closes https://github.com/vrchatapi/specification/issues/385
> Add usx region

- openapi/components/schemas/PerformanceRatings.yaml
- openapi/components/schemas/UnityPackage.yaml
It seems to only exist in the avatar unitypackage. Please let me know if I'm adding it in the wrong place.
> Add PerformanceRating to UnityPackage

- openapi/components/schemas/LimitedUser.yaml
After my missunderstanding what i needed to do in the last pull request and the amount of changes that happend i decived to recheck what still is diffrent and create a new merge request on the current main ^^ thanks for the one who helped clarifying what i missunderstood on discord ^^ i hope i did it correctly this time just added the last_login field that is still missing since my last pull request
> Added 'last_login' to 'LimitedUser' schema

- openapi/components/schemas/UserSubscription.yaml
Property removed at:
https://github.com/vrchatapi/specification-test/commit/cf7cd6898cbf932c519b20dcaf68af870ecfebf9#diff-5e97484f7e3e0be0041e15ff397ec968d39041fbeb9b9c25d9d1b498372d33d9L4
New property added at:
https://github.com/vrchatapi/specification-test/commit/38ddb87037ff0cc3e0af07b990e8972c9091562e#diff-5e97484f7e3e0be0041e15ff397ec968d39041fbeb9b9c25d9d1b498372d33d9R5
> Rename isGiftDrop to isBulkGift

- openapi/components/schemas/AgeVerificationStatus.yaml
- openapi/components/schemas/AgeVerified.yaml
Changed description to align with the new informations.
> Fix age verify description

- openapi/components/schemas/CurrentUser.yaml
https://github.com/vrchatapi/specification-test/commit/91c4767786d421a7cba31a965990239e311a0021
> Add platform history

- openapi/components/codeSamples/favorites.yaml
- openapi/components/paths/favorites.yaml
closes: https://github.com/vrchatapi/specification/issues/416
> Remove getfavorite endpoint

- openapi/components/schemas/Instance.yaml
> Make gameserverversion optional as it isnt returned for create instance

- openapi/components/codeSamples/prints.yaml
- openapi/components/parameters.yaml
- openapi/components/paths.yaml
- openapi/components/paths/prints.yaml
- openapi/components/responses/prints/PrintListResponse.yaml
- openapi/components/responses/prints/PrintResponse.yaml
- openapi/components/responses/prints/UnableToRequestOtherUsersPrintsError.yaml
- openapi/components/schemas/Print.yaml
- openapi/components/schemas/PrintID.yaml
- openapi/components/tags.yaml
There is also a post at api/1/prints/ to make a new one and api/1/prints/prnt_ID to edit one, but I don't know how to make those work, I keep getting 
{
"error": {
"message": "\"No image given in request.\"",
"status_code": 400
}
}
> Add prints api

- openapi/components/schemas/GroupPermissions.yaml
Reverts vrchatapi/specification#484
> Revert "Adds calendar management permission to group schemas"

- openapi/components/parameters.yaml
- openapi/components/paths.yaml
- openapi/components/paths/calendar.yaml
- openapi/components/schemas/CalendarEvent.yaml
> Add calendar search for events

- openapi/components/schemas/GroupPermissions.yaml
Add group-instance-calendar-link to Permissions enum
> Adds new calendar link permission

- openapi/openapi.yaml
Please also tag this so it gets released
> Bump API version from 1.20.3 to 1.20.4
